### ISSUE TITLE
Can we implement your Flowerpot plugin into ImagicalMine?

### ISSUE THREAD

**Issue by inxomnyaa** [beito123/PocketMine-MP-Plugins#2]
Hey! Muqsit from the PocketMine forums showed me your plugin flowerpot.
I was working on them too, but they wether changed into soulsand or disappeared.
Me, as a team member of @ImagicalCorporation would love to add your plugin into our version of pocketMine called ImagicalMine (for 0.13.0)
Would you be okay with that?

**Comment by beito123** [comment]
ok.

**Comment by inxomnyaa** [comment]
Cool! Thanks alot!

**Comment by legoboy0215** [comment]
THANKS!
