### ISSUE TITLE
itemframeblock

### ISSUE THREAD

**Issue by inxomnyaa** [beito123/PocketMine-MP-Plugins#8]
```
        if($this->getSide($faces[$this->meta] ?? -1)->getId() === Item::AIR){//
```

why the ??

**Comment by beito123** [comment]
It is doing just in case. :)
It works even if it is edited by such as the World editor.

``` php
$side = isset($faces[$this->meta]) ? $faces[$this->meta]:-1;
```

**Comment by inxomnyaa** [comment]
And.. what is **??** doing? 
Also, noteblocks dont play sounds for me (new issue?)

**Comment by beito123** [comment]
It is a new feature of php7. 
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

ok, i will try. thank :)

**Comment by inxomnyaa** [comment]
@beito123 ah, thanks, thats why i didnt knew it :)
