### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by ghost** [beito123/PocketMine-MP-Plugins#9]
For your sit plugin, what is the chair ? Where the players has to tap to go in sitposition ?

**Comment by inxomnyaa** [comment]
None actually, its only per command using /sit
I have a modified one which makes you sit when you sneak on chairs, but tap is annoying in creative building etc

**Comment by beito123** [comment]
Use /sit commnd at the position you want to sit. :)

Thanks dan. ;)

**Comment by inxomnyaa** [comment]
@beito123 Welcome

**Comment by ghost** [comment]
@beito123 @thebigsmileXD Can you add : When you tap on a pet it pit you it sit position ?

**Comment by inxomnyaa** [comment]
hmm.. i think that should be another plugin.

**Comment by beito123** [comment]
ummm... I also think that don't match with the plugin. :(
and sorry for reply late.

**Comment by inxomnyaa** [comment]
http://wolvesfortress.de/de_de/plugins/Sit_v1.0.2.phar
This is my modified version.
